#!/bin/bash

echo "generate and publish calendar"
npm run generate || exit 1

echo "deploy calendar"
scp ${TRAVIS_BUILD_DIR}/dist/calendar.{ics,json} web-standards.ru:

echo "send to webstandards_events"
git diff --name-only HEAD^ | \
 xargs -L1 | grep '^events.*' | \
 xargs npx github:web-standards-ru/calendar-bot --token="$TOKEN" --channel=@webstandards_events
